server:
  port: 8021

spring:
  resources:
    static-locations: classpath:/static/, classpath:/views/
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mapper/**/*.xml